services:
  express-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: express_container
    ports:
      - "3000:3000" # Map container's port 3000 to host's port 3000
    environment:
      - PORT=3000
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    env_file:
      - ./.env
