services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: sqlserver_container
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "YourStrong!Passw0rd"
    ports:
      - "0.0.0.0:1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: express_backend
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    depends_on:
      - sqlserver

volumes:
  sqlserver_data:
    driver: local
