services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: sqlserver_container
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "YourStrong!Passw0rd"
    ports:
      - "0.0.0.0:1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    restart: always

  initialize:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: initialize_container
    command: ["node", "initialize.js"]
    depends_on:
      - sqlserver

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend_container
    command: ["node", "server.js"]
    depends_on:
      - sqlserver
      - initialize
    restart: always
    ports:
      - "3000:3000"

volumes:
  sqlserver_data:
    driver: local
